apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: {{ .Values.command }}
        args: {{ .Values.args }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: NODE_ENV
          value: "{{ .Values.env.NODE_ENV }}"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        livenessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - -f
            - node
        readinessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - -f
            - node
      strategy:
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
