apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 8080
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
